### ISSUE TITLE
updateMeters and averagePowerForChannel equivalents for Novocaine?

### ISSUE THREAD

**Issue by TanejaArun** [alexbw/novocaine#125]
Hi Alex

I need to show visualizer for which i need **updateMeters** and **averagePowerForChannel** methods. In an example of visualizer, they are using AVAudioPlayer. 

Please help me with getting the equivalents of these methods for Novocaine.

Thanks

**Comment by alexbw** [comment]
Novocaine only provides methods for grabbing and sending audio to the mic.
Any audio processing methods you will have to write separately.

**Comment by TanejaArun** [comment]
Thanks Alex. I am closing this thread, will update you if i need further assistance.
