### ISSUE TITLE
adding Novocaine to my project

### ISSUE THREAD

**Issue by rossbertsch** [alexbw/novocaine#26]
Hi,
  First off I would like to say great work and thank you for contributing this open source project, it is much appreciated by many of us.

I'm having a little trouble adding this to my iOS project, and actually i'm not quite sure if this is the best solution for me so I thought I would ask you since you seem to know a good bit about audio.

I am designing an application for kids that allows them to play along with certain songs/stories. I dont need to do any complicated audio processing, all the sounds are going to be pre recorded samples in specific keys. The only manipulation to the audio that I'll need is that I'll need to play up to 6 different audio clips at the same time and I will need to be able to adjust the levels of each audio track.

I tried adding your code to my project but I am having trouble with dependencies... and the whole .mm thing. If you could include a short guide on the easiest way to add this to an existing project it would be greatly appreciated.

**Comment by sudheerkumar109** [comment]
I have tried everything . but I am not able to integrate this Novocaine. 
Followed all the steps mentioned above. 

#if defined (USING_IOS)
@interface Novocaine : NSObject <UIAlertViewDelegate> 

saying Cannot find protocol declaration for UIAlertViewDelegate

Can somebody help me in integrating this Novocaine files please.
