### ISSUE TITLE
output on iOS is mono

### ISSUE THREAD

**Issue by morganpackard** [alexbw/novocaine#28]
Am I crazy? Has this always been the case and nobody noticed until now? Novocaine is outputting audio in mono through headphones.  `ioData->mBuffers[0].mNumberChannels` is 1.

If I figure out why, I'll make a note, and, with luck and a good attitude, commit some code.

**Comment by MohdFarhanKhan** [comment]
Hi,

Am novocain addicted new ios developer. Am using novocain in an ios project. App is recording 2 channel audio. Client records audio with a sensor device. That sensor also can work as receiver. Client's requirement is to send a tone to sensor not speaker while recording from sensor. Please help me how to send tone to sensor.
