### ISSUE TITLE
Crash on iOS 8

### ISSUE THREAD

**Issue by el-hoshino** [alexbw/novocaine#95]
I tested my app on iOS 8 GM, and it sometimes gets crashed at ExtAudioFileRead(self.inputFile, &framesRead, &incomingAudio); in bufferNewAudio. The crash is EXC_BAD_ACCESS. It's not every time, just sometimes. I tested it both build on Xcode 5 and Xcode 6. The hardware is iPod touch 5th generation (I haven't test it on other devices yet but since it looks like a memory issue, probably it's very liked to happen on iPod touch 5 and iPad 3rd gen often).

Please let me know if you need any further information.

**Comment by alexbw** [comment]
Still an issue? Resolved?

**Comment by el-hoshino** [comment]
sorry for being late. actually I'm not on that project anymore, so I'm not sure if it's resolved but I don't hear about this issue from the developers so I guess it should be resolved.
